### ISSUE TITLE
The Alchemist keeps crashing my game when the mob starts appearing in a few waves.

### ISSUE THREAD

**Issue by dennisjosh16** [OhDricky/Illager-Expansion#2]
---- Minecraft Crash Report ----
// There are four lights!

Time: 4/13/22, 1:17 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
	at me.sandbox.entity.AlchemistEntity.cancelEffect(AlchemistEntity.java:140)
	at me.sandbox.entity.AlchemistEntity.removeEffectsinCloud(AlchemistEntity.java:150)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.sandbox.entity.AlchemistEntity.method_5958(AlchemistEntity.java:189)
	at net.minecraft.class_1308.method_6023(class_1308.java:759)
	at net.minecraft.class_1309.method_6007(class_1309.java:2609)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
	at me.sandbox.entity.AlchemistEntity.cancelEffect(AlchemistEntity.java:140)
	at me.sandbox.entity.AlchemistEntity.removeEffectsinCloud(AlchemistEntity.java:150)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.sandbox.entity.AlchemistEntity.method_5958(AlchemistEntity.java:189)
	at net.minecraft.class_1308.method_6023(class_1308.java:759)
	at net.minecraft.class_1309.method_6007(class_1309.java:2609)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: illagerexp:alchemist (me.sandbox.entity.AlchemistEntity)
	Entity ID: 16583
	Entity Name: Kakos Nupp
	Entity's Exact location: -51.36, 63.00, -461.49
	Entity's Block location: World: (-52,63,-462), Section: (at 12,15,2 in -4,3,-29; chunk contains blocks -64,-64,-464 to -49,319,-449), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['overlord_killer25'/7, l='ServerLevel[The Legend of SussyWussy]', x=-62.93, y=63.00, z=-450.49]]
	Chunk stats: 4052
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,81,0), Section: (at 0,1,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2448782 game time, 3414057 day time
	Level name: The Legend of SussyWussy
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 44870 (now: false), thunder time: 51298 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by OhDricky** [comment]
Thank you for letting me know! I will have a fix in the next update. I will leave this thread open until I have resolved the issue.

**Comment by OhDricky** [comment]
Hopefully I have fixed the issue, it will be included in the next version. Closing the thread!
