### ISSUE TITLE
Error:  ImbuingTableScreenHandler, ExceptionInInitializerError null

### ISSUE THREAD

**Issue by kapitanluffy** [OhDricky/Illager-Expansion#5]
Hi. Can you help debug this? Player reported he was just crafting.

```
[22:43:52] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
	at me.sandbox.gui.ImbuingTableScreenHandler.<init>(ImbuingTableScreenHandler.java:39) ~[illager_expansion-0.1.5.jar:?]
	at me.sandbox.gui.ImbuingTableScreenHandler.<init>(ImbuingTableScreenHandler.java:35) ~[illager_expansion-0.1.5.jar:?]
	at me.sandbox.block.custom.ImbuingTableBlock.lambda$createScreenHandlerFactory$0(ImbuingTableBlock.java:73) ~[illager_expansion-0.1.5.jar:?]
	at net.minecraft.class_747.createMenu(class_747.java:25) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_17355(class_3222.java:1031) ~[server-intermediary.jar:?]
	at me.sandbox.block.custom.ImbuingTableBlock.method_9534(ImbuingTableBlock.java:48) ~[illager_expansion-0.1.5.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:menu / illagerexp:imbuing_table])
	at net.minecraft.class_2370.method_40274(class_2370.java:80) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_31051(class_2370.java:90) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:134) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_39197(class_2378.java:471) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10230(class_2378.java:467) ~[server-intermediary.jar:?]
	at net.fabricmc.fabric.api.screenhandler.v1.ScreenHandlerRegistry.registerSimple(ScreenHandlerRegistry.java:90) ~[fabric-screen-handler-api-v1-1.2+1f6558e860-18d3c1f3c9ab853d.jar:?]
	at me.sandbox.gui.ModdedScreenHandler.<clinit>(ModdedScreenHandler.java:11) ~[illager_expansion-0.1.5.jar:?]
	... 25 more
```

**Comment by kapitanluffy** [comment]
Tested it by accessing the imbuing table and it crashed

**Comment by OhDricky** [comment]
Thank you for the issue report and the pull request you submitted previously! I will take a look at this and get back with you. I will close the issue once it has been fixed. Thanks again!!

**Comment by OhDricky** [comment]
Can you provide detailed steps as to how you encountered this issue? Thanks!

**Comment by kapitanluffy** [comment]
It happens when the player tries to access the imbuing table. Knowing him, he is probably maxing out something.

**Comment by OhDricky** [comment]
Ok! Is the issue recurring or has it only happened once?

**Comment by kapitanluffy** [comment]
It is recurring. For now, I told the players not to use an imbuing table.
